redis: &redis
  adapter: redis
  uri: redis://localhost:6379

development: *redis

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: order_history_api_production
